### ISSUE TITLE
Anonymous classes

### ISSUE THREAD

**Issue by hannesvdvreken** [spatie/7to5#10]
I tried this approach for replacing anonymous classes:

```php
$foo = new class {
    public function bar()
    {
        return 'bar';
    }
}

$foo->bar();
```

### First attempt: JS style

```php
$foo = call_user_func(function () {
    $thisObject = new \stdClass();
    $thisObject->bar = ()
    {
        return 'bar';
    }

    return $thisObject;
}

$foo->bar();
```

But this will never work. More reading:
http://stackoverflow.com/questions/11503212/add-method-in-an-std-object-in-php
http://stackoverflow.com/questions/2938004/how-to-add-a-new-method-to-a-php-object-on-the-fly

TLDR: you cannot add methods on `new stdClass` object to be invoke via the `object->method()` syntax.
You can with `call_user_func($object->method)` but it would be too hard to find all places where a method will be invoke on that object.

### Second attempt: declare a new class anyway, but give it a prefixed name
 
So I tried with defining a new class, give it a long name, and it works:

```php
$foo = call_user_func_array(function () {
    class Spatie_Php7to5_Anonymous_ABCDEF1234
    {
        public function bar()
        {
            return 'bar';
        }
    }

    $reflection = new \ReflectionClass('Spatie_Php7to5_Anonymous_ABCDEF1234');
    return $reflection->newInstanceArgs(func_get_args());
}, []);
```

This allows you to copy the entire class body and invoke a new object. Question is: do we want this?

PS: wrapping the declaration in a namespace with `namespace Spatie\7to5\Anon { class ... {} }` is impossible (http://php.net/manual/en/language.namespaces.definitionmultiple.php)

### Maybe another option: wrapping in one class with magic methods

Another way to do this would be to provide a special class:

```php
$foo = new Spatie\7to5\Helper\AnonymousClassWrapper($constructor, $methods, $attributes, $constructorArguments);
```
Which uses the `__call` method and `__get` to expose all public attributes and methods. This would require a lot of rewriting the AST, though.

What do you think?

**Comment by jenssegers** [comment]
`Spatie_Php7to5_Anonymous_ABCDEF1234` looks like the easiest option. Go for it :)

**Comment by freekmurze** [comment]
Great research on the various approaches, @hannesvdvreken.

Yet another option: you could [writing all anonymous classes at the top of the file and just use them like regular classes](https://github.com/jaytaph/Transphpile/blob/716cda18469e0e5fb7dc76e70381aee2316de9e7/lib/Transphpile/Transpile/Visitors/Php70/AnonymousClassVisitor.php).

**Comment by freekmurze** [comment]
Initial support for [replacing anonymous classes by regular classes](https://github.com/spatie/7to5/blob/ef6def9/src/NodeVisitors/AnonymousClassReplacer.php) has been added.  It'll detect an anonymous class, will give it a name, and move it to the top of the file after any imports or declares. I also provided a test to make sure it works.

Thoughts?

**Comment by freekmurze** [comment]
O, I forgot to convert the php 7 features use inside an anonymous class. Will fix that soon.

**Comment by freekmurze** [comment]
Code inside anonymous classes will be converted to PHP 5 now as well. 

Unless you have some remarks, I'm ready to close this issue.

**Comment by hannesvdvreken** [comment]
:whale: :ship:

**Comment by freekmurze** [comment]
🙏
