### ISSUE TITLE
Undefined function ends_with

### ISSUE THREAD

**Issue by BarthyB** [spatie/7to5#17]
Hello!

Unfortunately, php7to5 spits out this error:

> Call to undefined function Spatie\Php7to5\Console\ends_with() [...]

I looked into the code, there is no such function. I think that should be a quick fix..

**Comment by freekmurze** [comment]
This function is included in `illuminate/support` that gets pulled in when running composer. Did you run `composer install`? Which version of `illuminate/support` is installed?

**Comment by BarthyB** [comment]
Dear Freek,

I'm sorry for never having answered your comment.
I had completely forgotten to reply since I had found a way to get my stuff to work without your awesome 7to5 bundle.

Thanks a lot for helping though.
To answer your question:

I did not run `composer install`, but I did use `composer require` to install the bundle. Shouldn't this have lead to the same result?

Greetings,

Barthy

**Comment by laravelish** [comment]
i have the same error, i ran `composer global require spatie/7to5`

**Comment by freekmurze** [comment]
Does your vendor contain an `illuminate/support` subdir?
