### ISSUE TITLE
Undefined Function

### ISSUE THREAD

**Issue by Wakasaki** [spatie/7to5#18]
I have read the other closed Issues but it doesn't help me.

The error is 

> PHP Fatal error:  Uncaught Error: Call to undefined function Spatie\Php7to5\Console\ends_with() in C:\Users\...\...\Composer\vendor\spatie\7to5\src\Console\ConvertCommand.php:136

I  did use `composer global require` to install the bundle.
I saw that into Composer\Vendor folder there is not any illuminate/support subdir.

How can I resolve this isssue?

Any help is appreciated, thanks

**Comment by grahampople** [comment]
I get the same issue.

**Comment by freekmurze** [comment]
Fixed in v1.0.1
