### ISSUE TITLE
Suggestion: Convert type hints to checks in method

### ISSUE THREAD

**Issue by oligriffiths** [spatie/7to5#19]
Scalar type hints for arguments and return value could be converted into checks within the function itself, e.g:

```php
function foo(string $bar) : string {

  if (is_string($bar)) {
    throw new \InvalidArgumentException(__FUNCTION__.' expects paramater 0 to be a string');
  }

  $return_val = 1;

  if (!is_string($return_val)) {
    throw new \UnexpectedValueException(__FUNCTION__.' expects return value to be a string');
  }

  return $return_val;
}
```

**Comment by freekmurze** [comment]
Yup, you're right. If you want to work on this I'd accept a PR with tests that adds this the package.

Or you could just use this more feature rich convertor that already supports that functionality: https://github.com/jaytaph/Transphpile
