### ISSUE TITLE
Class constants visibility

### ISSUE THREAD

**Issue by OndraM** [spatie/7to5#30]
Looks like class constants visibility (added in PHP 7.1) are not converted (ie. removed).

This is invalid in PHP <7.1
```php
class Foo
{
    protected const FOO = 'foo';
    public const BAR = 'bar';
    private const BAZ = 'baz';
}
```

Or maybe this is out of the scope of this project (because it is 7.1 feature)?

**Comment by freekmurze** [comment]
This package only works for PHP 7.0 code. I've updated the readme to make this clear. However, I'd accept fully tested PR that fixes your reported issue.

**Comment by OndraM** [comment]
For reference, this was fixed in https://github.com/spatie/7to5/pull/37
