### ISSUE TITLE
Please can you add ::class, ...$args and [] to array replacers

### ISSUE THREAD

**Issue by drnkwati** [spatie/7to5#35]
Hi. 
This a great package. Please can you add support for following syntax reverting:
Variadic functions via ...
Argument unpacking via ... 
Class name resolution via ::class

thanks

**Comment by sebastiandedeyne** [comment]
Those aren't php7 functions so I don't see why we'd transpile those here.

**Comment by drnkwati** [comment]
You are wrong bro.
This is a tool, any new functionality added to it will be a plus to the package.
By the way, you cannot stop developers working on PHP projects from using these new features.
However, I will be grateful if you can recommend a similar tool with these features.
If you are closing this, then you should have another tool that can handle these 
thanks
