### ISSUE TITLE
Convert scalar type hints to additional PHP 5 checks

### ISSUE THREAD

**Issue by filips123** [spatie/7to5#46]
Convert scalar type hints to additional PHP 5 checks. They are currently just removed.

For example, function:
```php
function myFunction(string $name = 'World')
{
    return 'Hello ' . $name;
}
```

should be converted to something like:
```php
function myFunction($name = 'World')
{
    if (!is_string($name)) {
        throw new InvalidArgumentException('Argument `$name` is not string');
    }

    return 'Hello ' . $name;
}
```

Exception type should be `InvalidArgumentException` or `TypeError`. It's message should be something like `Argument 2 passed to sum() must be of the type integer, string given, ...`.

**Comment by freekmurze** [comment]
We are not maintaining this package any more. Feel free to fork our code and maintain your own copy.
