### ISSUE TITLE
Make it crash on things that are not yet implemented

### ISSUE THREAD

**Issue by freekmurze** [spatie/7to5#8]
We could tag the package 1.0.0 if we can make it crash on all features that currently are not supported.

I'm thinking of anonymous classes, deprecated functions, throwable and so on.

We can add more features with point releases.

Thoughts @hannesvdvreken?

**Comment by hannesvdvreken** [comment]
Agreed. Some things will be impossible to spot though.
For example: Generator:: getReturn() is a new method but it will be impossible to detect where it is used. Some things might by polyfilled though, so then it's not useful to remove it.

http://php.net/manual/en/migration70.php

**Comment by freekmurze** [comment]
Going to close this for now. Feel free to reopen this if you're using the package and it produces errors on something unsupported.
